name = "mlengine"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Samuel Leonetti", "Owen Wienczkowski"]
maintainers = ["Samuel Leonetti <samleo312@gmail.com>", "Owen Wienczkowski <wxyzowen@gmail.com>"]
maintainers-logins = ["samleo312", "OwenWxyz"]
[[depends-on]]
orka_numerics = "^1.0.0"
